// Icon Registry - Centralized icon definitions and exports
// Provides unified way to import and use icons from different libraries (Huge Icons & Hero Icons)

// Huge Icons - Import first, then export with aliases
import {
  AddIcon,
  AiPhone01Icon,
  ArrowDown01Icon,
  ArrowLeft01Icon,
  ArrowLeft02Icon,
  ArrowRight01Icon,
  ArrowRight02Icon,
  ArrowUp01Icon,
  BookmarkIcon,
  CalendarIcon,
  CancelIcon,
  CheckmarkCircleIcon,
  ClockIcon,
  ComputerIcon,
  CreditCardIcon,
  DarkModeIcon,
  DeleteIcon,
  DownloadIcon,
  EditIcon,
  EyeIcon,
  File01Icon,
  FileIcon,
  FilterIcon,
  FloppyDiskIcon,
  FolderIcon,
  FolderOpenIcon,
  HelpCircleIcon,
  Home01Icon,
  ImageIcon,
  LocationIcon,
  LockIcon,
  LoginIcon,
  LogoutIcon,
  MailIcon,
  Menu01Icon,
  Menu02Icon,
  Menu03Icon,
  MessageIcon,
  MoneyIcon,
  MoonIcon,
  NotificationIcon,
  PauseIcon,
  PlayIcon,
  PlusSignIcon,
  SearchIcon,
  SettingsIcon,
  ShareIcon,
  ShieldIcon,
  StarIcon,
  SunIcon,
  UploadIcon,
  UserCircleIcon,
  UserIcon,
  UserSettingsIcon,
  VideoIcon,
} from "@hugeicons/core-free-icons";

// Export all Huge Icons with original names
export {
  ArrowDown01Icon,
  ArrowLeft01Icon,
  ArrowRight01Icon,
  ArrowRight02Icon,
  ArrowLeft02Icon,
  ArrowUp01Icon,
  AiPhone01Icon,
  BookmarkIcon,
  CalendarIcon,
  CancelIcon,
  CheckmarkCircleIcon,
  ClockIcon,
  ComputerIcon,
  CreditCardIcon,
  DarkModeIcon,
  DeleteIcon,
  DownloadIcon,
  EditIcon,
  File01Icon,
  FileIcon,
  FilterIcon,
  FloppyDiskIcon,
  FolderIcon,
  FolderOpenIcon,
  HelpCircleIcon,
  Home01Icon,
  ImageIcon,
  LocationIcon,
  LockIcon,
  LoginIcon,
  LogoutIcon,
  MailIcon,
  Menu01Icon,
  Menu02Icon,
  Menu03Icon,
  MessageIcon,
  MoneyIcon,
  MoonIcon,
  NotificationIcon,
  PauseIcon,
  PlayIcon,
  PlusSignIcon,
  AddIcon,
  SearchIcon,
  SettingsIcon,
  ShareIcon,
  ShieldIcon,
  StarIcon,
  SunIcon,
  UploadIcon,
  UserCircleIcon,
  UserIcon,
  UserSettingsIcon,
  VideoIcon,
  EyeIcon,
};

// Export with simpler aliases for convenience
export {
  ArrowRight01Icon as ArrowRightIcon,
  ArrowLeft01Icon as ArrowLeftIcon,
  ArrowDown01Icon as ArrowDownIcon,
  ArrowUp01Icon as ArrowUpIcon,
  AiPhone01Icon as PhoneIcon,
  UserSettingsIcon as UserSettingIcon,
  CheckmarkCircleIcon as CheckCircleIcon,
};

// Hero Icons - Import and re-export with Hero prefix
import {
  BanknotesIcon,
  BellIcon,
  BriefcaseIcon,
  ChatBubbleLeftRightIcon,
  CheckIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  CodeBracketIcon,
  Cog6ToothIcon,
  ComputerDesktopIcon,
  DocumentTextIcon,
  EyeSlashIcon,
  ArrowLeftIcon as HeroArrowLeftIconBase,
  ArrowRightIcon as HeroArrowRightIconBase,
  EyeIcon as HeroEyeIconBase,
  MoonIcon as HeroMoonIconBase,
  SunIcon as HeroSunIconBase,
  UserIcon as HeroUserIconBase,
  HomeIcon,
  LockClosedIcon,
  LockOpenIcon,
  MagnifyingGlassIcon,
  PencilIcon,
  PlusIcon,
  SparklesIcon,
  TrashIcon,
  UserGroupIcon,
  XMarkIcon,
} from "@heroicons/react/24/outline";

// Re-export Hero Icons with Hero prefix for consistency
export {
  HomeIcon as HeroHomeIcon,
  MagnifyingGlassIcon as HeroSearchIcon,
  BellIcon as HeroBellIcon,
  HeroUserIconBase as HeroUserIcon,
  Cog6ToothIcon as HeroSettingsIcon,
  HeroArrowRightIconBase as HeroArrowRightIcon,
  HeroArrowLeftIconBase as HeroArrowLeftIcon,
  ChevronRightIcon as HeroChevronRightIcon,
  ChevronLeftIcon as HeroChevronLeftIcon,
  ChevronDownIcon as HeroChevronDownIcon,
  ChevronUpIcon as HeroChevronUpIcon,
  XMarkIcon as HeroCloseIcon,
  CheckIcon as HeroCheckIcon,
  PlusIcon as HeroPlusIcon,
  PencilIcon as HeroEditIcon,
  TrashIcon as HeroDeleteIcon,
  HeroEyeIconBase as HeroEyeIcon,
  EyeSlashIcon as HeroEyeHideIcon,
  LockClosedIcon as HeroLockIcon,
  LockOpenIcon as HeroUnlockIcon,
  HeroSunIconBase as HeroSunIcon,
  HeroMoonIconBase as HeroMoonIcon,
  ComputerDesktopIcon as HeroComputerIcon,
  ChatBubbleLeftRightIcon as HeroQuoteIcon,
  BriefcaseIcon as HeroBriefcaseIcon,
  CodeBracketIcon as HeroCodeIcon,
  UserGroupIcon as HeroUsersIcon,
  BanknotesIcon as HeroBanknoteIcon,
  DocumentTextIcon as HeroFileTextIcon,
  SparklesIcon as HeroSparklesIcon,
};

// Export without Hero prefix for convenience (use in components)
export {
  PencilIcon as PenIcon,
  SparklesIcon,
  BriefcaseIcon,
  CodeBracketIcon as CodeIcon,
  UserGroupIcon as UsersIcon,
  BanknotesIcon as BanknoteIcon,
  DocumentTextIcon as FileTextIcon,
  ChatBubbleLeftRightIcon as QuoteIcon,
};

// Type exports for icon usage
export type { SVGProps } from "react";
